# Generated by Django 6.1 on 2026-08-30 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honeypot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attacklog',
            old_name='intent',
            new_name='attacker_ip',
        ),
        migrations.RenameField(
            model_name='attacklog',
            old_name='path',
            new_name='target_path',
        ),
        migrations.RemoveField(
            model_name='attacklog',
            name='ip_address',
        ),
        migrations.AddField(
            model_name='attacklog',
            name='classified_intent',
            field=models.CharField(default='Normal', max_length=100),
        ),
        migrations.AlterField(
            model_name='attacklog',
            name='payload',
            field=models.TextField(blank=True, null=True),
        ),
    ]
