# Generated by Django 6.1 on 2026-09-27 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honeypot', '0002_rename_intent_attacklog_attacker_ip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attacklog',
            name='risk_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='attacklog',
            name='session_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='attacklog',
            name='attacker_ip',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='attacklog',
            name='classified_intent',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='attacklog',
            name='payload',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
